name: publish courier contracts to nuget
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/Courier.Contracts/Courier.Contracts.csproj
          NUGET_KEY: ${{secrets.NUGET_KEY}}